# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utilities.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0011_django2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50, validators=[utilities.validators.TagValidator])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('content_type', 'object_id', 'name')]),
        ),
    ]
